### ISSUE TITLE
Where to set supercycling length?

### ISSUE THREAD

**Issue by bradyrx** [pwolfram/MPAS-Model#13]
Per @pwolfram , super-cycling should already be available for particles. 

**What is the most straightforward way to set (and thus vary) the super-cycling time length?**

I checked `Registry_lagrangian_particle_tracking.xml` and didn't find anything related to it. However, I did find the super-cycling section in `mpas_ocn_lagrangian_particle_tracking.F`.

**Comment by pwolfram** [comment]
@bradyrx, this is somewhat obscured.  Great question!  You need to change

`config_AM_lagrPartTrack_compute_interval = 'dt'`

to something like

```
config_dt = '00:10:00'
config_AM_lagrPartTrack_compute_interval = '0000_01:00:00'
```

See https://github.com/MPAS-Dev/MPAS/pull/1484 for more detail.  Does this make more sense?

**Comment by bradyrx** [comment]
@pwolfram ,

Before I send off these test cases, I want to make sure I'm doing this right. (Note the linked PR is broken)

Does `config_dt` modify the global time step? I haven't set this explicitly, so it currently runs at whatever default is. I imagine then that `compute_interval` should be a multiple of `config_dt`?

Assuming this is all correct, would these test cases work?

no supercycling
```
config_dt = '00:10:00'
config_AM_lagrPartTrack_compute_interval = 'dt'
```

1 hour supercycling
```
config_dt = '00:10:00'
config_AM_lagrPartTrack_compute_interval = '0000_01:00:00'
```

4 hour supercycling
```
config_dt = '00:10:00'
config_AM_lagrPartTrack_compute_interval = '0000_04:00:00'
```

8 hour supercycling
```
config_dt = '00:10:00'
config_AM_lagrPartTrack_compute_interval = '0000_08:00:00'
```

**Comment by pwolfram** [comment]
@bradyrx, `config_dt` modifies the global time step.  `config_AM_lagrPartTrack_compute_interval` is the LIGHT time step and this should be effectively `n*config_dt`, e.g.,

```
config_dt = '00:10:00'
config_AM_lagrPartTrack_compute_interval = '0000_01:00:00'
```

I believe the test cases should work, please let me know.

I've requested getting you access to MPAS-Dev/MPAS#1484

**Comment by pwolfram** [comment]
@bradyrx, please let me know when you are satisfied here and please feel free to close when this is the case.  Thanks!
